In [1]:
import numpy as np

0’dan 9’a kadar olan sayılardan bir numpy array oluşturun
ve bu array’in:

tipini

boyutunu (shape)

kaç elemanlı olduğunu yazdırın

In [4]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
print(arr.shape)

(10,)


In [7]:
print(arr.size)

10


In [8]:
arr1 = np.array([6,8,12,13,16,10,18])

In [10]:
print(type(arr1))

<class 'numpy.ndarray'>


In [12]:
print(arr1.size)

7


In [13]:
print(arr1.shape)

(7,)


Indexleme
arr = np.array([10, 20, 30, 40, 50])
İlk elemanı alın

Son elemanı alın

Ortadaki elemanı alın
Amaç: arr[i], negatif index

In [14]:
arr2= np.array([10,20,30,40,50])

In [15]:
print(arr[0])

0


In [16]:
print(arr[4])

4


In [17]:
print(arr[2])

2


Sabit array’ler

10 elemanlı, tamamı 1 olan bir array oluşturun

3x3’lük, tamamı 0 olan bir array oluşturun

In [18]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

arr = np.array([1,2,3,4,5,6,7,8,9])
İlk 5 elemanı alın

Son 3 elemanı alın

Sadece çift indextekileri alın

In [22]:
arr3 = np.array([1,2,3,4,5,6,7,8,9])

In [23]:
print(arr[0:6])

[0 1 2 3 4 5]


In [24]:
print(arr[5:])

[5 6 7 8 9]


In [25]:
print(arr[6:])

[6 7 8 9]


In [26]:
print(arr[7:])

[7 8 9]


In [28]:
print(arr[0:9:2])

[0 2 4 6 8]


arr = np.array([1, 2, 3, 4, 5])
Tüm elemanları 2 ile çarpın

Tüm elemanların karesini alın

Tüm elemanlara 10 ekleyin

In [29]:
arr4 = np.array([1,2,3,4,5])

In [31]:
print(arr4*2)

[ 2  4  6  8 10]


In [34]:
print(arr4**2)

[ 1  4  9 16 25]


In [33]:
print(arr4+10)

[11 12 13 14 15]


İki array ile işlem
a = np.array([1,2,3])
b = np.array([4,5,6])


a + b

a * b

a - b

In [35]:
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])

In [36]:
print(arr_a + arr_b)

[5 7 9]


In [37]:
print(arr_a * arr_b)

[ 4 10 18]


In [38]:
print(arr_a - arr_b)

[-3 -3 -3]


Boolean indexing
arr = np.array([10, 25, 30, 5, 60, 15])


20’den büyük olanları bulun

10 ile 40 arasında olanları bulun

In [39]:
arr5 = np.array([10,25,30,5,60,15])

In [43]:
arr5[arr5 > 20]

array([25, 30, 60])

In [46]:
arr5[(arr5>10)&(arr5<40)]

array([25, 30, 15])

Aynı array’de:

20’den küçük olanları 0 yapın

In [47]:
arr5 = np.array([10,25,30,5,60,15])

In [48]:
arr5[arr5<20]=0

In [49]:
print(arr5)

[ 0 25 30  0 60  0]


2D array

3x3’lük rastgele sayılardan oluşan bir matrix oluşturun

Bu matrix’in:

satır sayısını

sütun sayısını

toplam eleman sayısını yazdırın

In [51]:
mat = np.random.randint(0,10, size=(3,3))

In [52]:
print(mat)

[[2 8 3]
 [8 0 6]
 [5 1 8]]


In [54]:
print("satır sayisi:", mat.shape[0])

satır sayisi: 3


In [55]:
print("sütun sayisi:", mat.shape[1])

sütun sayisi: 3


In [56]:
print("toplam eleman:", mat.size)

toplam eleman: 9


mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
Ortadaki elemanı alın

İlk satırı alın

Son sütunu alın

In [57]:
mat1= np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [63]:
mat1[2,2]

np.int64(9)

In [62]:
print(mat1[1,1])

5


In [64]:
print(mat[0])

[2 8 3]


In [65]:
mat1[1,1]

np.int64(5)

In [66]:
print(mat[:,-1])

[3 6 8]


data = np.array([12, 15, 20, 22, 30, 35, 40])
Ortalama

Medyan

Standart sapma

Min & Max



In [67]:
data = np.array([12, 15, 20, 22, 30, 35, 40])

In [69]:
print("Ortalama:", np.mean(data))
print("Medyan", np.median(data))
print("Std:", np.std(data))
print("Max:", np.max(data))
print("Min:", np.min(data))

Ortalama: 24.857142857142858
Medyan 22.0
Std: 9.657396446374612
Max: 40
Min: 12


In [ ]:
data

Bulun:
1️⃣ Ortalama maaş
2️⃣ Medyan maaş
3️⃣ En düşük ve en yüksek maaş

In [70]:
salaries = np.array([30000, 45000, 50000, 60000, 75000,
                     80000, 90000, 120000, 150000])

In [73]:
print("Ortalama maaş: ", np.mean(salaries))
print("ortalama medyan: ", np.median(salaries))
print("min maaş: ", np.min(salaries))
print("max maaş: ", np.max(salaries))

Ortalama maaş:  77777.77777777778
ortalama medyan:  75000.0
min maaş:  30000
max maaş:  150000


Bulun:
1️⃣ 70.000 TL’den yüksek maaşlar
2️⃣ 50.000 – 100.000 TL arasındaki maaşlar

In [74]:
print(salaries>70000)

[False False False False  True  True  True  True  True]


In [75]:
salaries[salaries>70000]

array([ 75000,  80000,  90000, 120000, 150000])

In [78]:
salaries[(salaries>50000)&(salaries<100000)]

array([60000, 75000, 80000, 90000])

Yapın:

40.000’den küçük olanları 0 yapın


In [80]:
salaries[salaries<400000]=0

In [81]:
salaries

array([0, 0, 0, 0, 0, 0, 0, 0, 0])