In [1]:
import numpy as np

0’dan 9’a kadar olan sayılardan bir numpy array oluşturun
ve bu array’in:

tipini

boyutunu (shape)

kaç elemanlı olduğunu yazdırın

In [4]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
print(arr.shape)

(10,)


In [7]:
print(arr.size)

10


In [8]:
arr1 = np.array([6,8,12,13,16,10,18])

In [10]:
print(type(arr1))

<class 'numpy.ndarray'>


In [12]:
print(arr1.size)

7


In [13]:
print(arr1.shape)

(7,)


Indexleme
arr = np.array([10, 20, 30, 40, 50])
İlk elemanı alın

Son elemanı alın

Ortadaki elemanı alın
Amaç: arr[i], negatif index

In [14]:
arr2= np.array([10,20,30,40,50])

In [15]:
print(arr[0])

0


In [16]:
print(arr[4])

4


In [17]:
print(arr[2])

2


Sabit array’ler

10 elemanlı, tamamı 1 olan bir array oluşturun

3x3’lük, tamamı 0 olan bir array oluşturun

In [18]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

arr = np.array([1,2,3,4,5,6,7,8,9])
İlk 5 elemanı alın

Son 3 elemanı alın

Sadece çift indextekileri alın

In [22]:
arr3 = np.array([1,2,3,4,5,6,7,8,9])

In [23]:
print(arr[0:6])

[0 1 2 3 4 5]


In [24]:
print(arr[5:])

[5 6 7 8 9]


In [25]:
print(arr[6:])

[6 7 8 9]


In [26]:
print(arr[7:])

[7 8 9]


In [28]:
print(arr[0:9:2])

[0 2 4 6 8]


arr = np.array([1, 2, 3, 4, 5])
Tüm elemanları 2 ile çarpın

Tüm elemanların karesini alın

Tüm elemanlara 10 ekleyin

In [29]:
arr4 = np.array([1,2,3,4,5])

In [31]:
print(arr4*2)

[ 2  4  6  8 10]


In [34]:
print(arr4**2)

[ 1  4  9 16 25]


In [33]:
print(arr4+10)

[11 12 13 14 15]


İki array ile işlem
a = np.array([1,2,3])
b = np.array([4,5,6])


a + b

a * b

a - b

In [35]:
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])

In [36]:
print(arr_a + arr_b)

[5 7 9]


In [37]:
print(arr_a * arr_b)

[ 4 10 18]


In [38]:
print(arr_a - arr_b)

[-3 -3 -3]


Boolean indexing
arr = np.array([10, 25, 30, 5, 60, 15])


20’den büyük olanları bulun

10 ile 40 arasında olanları bulun

In [39]:
arr5 = np.array([10,25,30,5,60,15])

In [43]:
arr5[arr5 > 20]

array([25, 30, 60])

In [46]:
arr5[(arr5>10)&(arr5<40)]

array([25, 30, 15])

Aynı array’de:

20’den küçük olanları 0 yapın

In [47]:
arr5 = np.array([10,25,30,5,60,15])

In [48]:
arr5[arr5<20]=0

In [49]:
print(arr5)

[ 0 25 30  0 60  0]


2D array

3x3’lük rastgele sayılardan oluşan bir matrix oluşturun

Bu matrix’in:

satır sayısını

sütun sayısını

toplam eleman sayısını yazdırın

In [51]:
mat = np.random.randint(0,10, size=(3,3))

In [52]:
print(mat)

[[2 8 3]
 [8 0 6]
 [5 1 8]]


In [54]:
print("satır sayisi:", mat.shape[0])

satır sayisi: 3


In [55]:
print("sütun sayisi:", mat.shape[1])

sütun sayisi: 3


In [56]:
print("toplam eleman:", mat.size)

toplam eleman: 9


mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
Ortadaki elemanı alın

İlk satırı alın

Son sütunu alın

In [57]:
mat1= np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [63]:
mat1[2,2]

np.int64(9)

In [62]:
print(mat1[1,1])

5


In [64]:
print(mat[0])

[2 8 3]


In [65]:
mat1[1,1]

np.int64(5)

In [66]:
print(mat[:,-1])

[3 6 8]


data = np.array([12, 15, 20, 22, 30, 35, 40])
Ortalama

Medyan

Standart sapma

Min & Max



In [67]:
data = np.array([12, 15, 20, 22, 30, 35, 40])

In [69]:
print("Ortalama:", np.mean(data))
print("Medyan", np.median(data))
print("Std:", np.std(data))
print("Max:", np.max(data))
print("Min:", np.min(data))

Ortalama: 24.857142857142858
Medyan 22.0
Std: 9.657396446374612
Max: 40
Min: 12


In [ ]:
data

Bulun:
1️⃣ Ortalama maaş
2️⃣ Medyan maaş
3️⃣ En düşük ve en yüksek maaş

In [70]:
salaries = np.array([30000, 45000, 50000, 60000, 75000,
                     80000, 90000, 120000, 150000])

In [73]:
print("Ortalama maaş: ", np.mean(salaries))
print("ortalama medyan: ", np.median(salaries))
print("min maaş: ", np.min(salaries))
print("max maaş: ", np.max(salaries))

Ortalama maaş:  77777.77777777778
ortalama medyan:  75000.0
min maaş:  30000
max maaş:  150000


Bulun:
1️⃣ 70.000 TL’den yüksek maaşlar
2️⃣ 50.000 – 100.000 TL arasındaki maaşlar

In [74]:
print(salaries>70000)

[False False False False  True  True  True  True  True]


In [75]:
salaries[salaries>70000]

array([ 75000,  80000,  90000, 120000, 150000])

In [78]:
salaries[(salaries>50000)&(salaries<100000)]

array([60000, 75000, 80000, 90000])

Yapın:

40.000’den küçük olanları 0 yapın


In [80]:
salaries[salaries<400000]=0

In [81]:
salaries

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("11-athlete_events.csv")

In [5]:
df

ID                      Name Sex   Age  Height  Weight  \
0            1                 A Dijiang   M  24.0   180.0    80.0   
1            2                  A Lamusi   M  23.0   170.0    60.0   
2            3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN   
3            4      Edgar Lindenau Aabye   M  34.0     NaN     NaN   
4            5  Christine Jacoba Aaftink   F  21.0   185.0    82.0   
...        ...                       ...  ..   ...     ...     ...   
271111  135569                Andrzej ya   M  29.0   179.0    89.0   
271112  135570                  Piotr ya   M  27.0   176.0    59.0   
271113  135570                  Piotr ya   M  27.0   176.0    59.0   
271114  135571        Tomasz Ireneusz ya   M  30.0   185.0    96.0   
271115  135571        Tomasz Ireneusz ya   M  34.0   185.0    96.0   

                  Team  NOC        Games  Year  Season            City  \
0                China  CHN  1992 Summer  1992  Summer       Barcelona   
1                China  CHN  2012 Summer  2012  Summer          London   
2              Denmark  DEN  1920 Summer  1920  Summer       Antwerpen   
3       Denmark/Sweden  DEN  1900 Summer  1900  Summer           Paris   
4          Netherlands  NED  1988 Winter  1988  Winter         Calgary   
...                ...  ...          ...   ...     ...             ...   
271111        Poland-1  POL  1976 Winter  1976  Winter       Innsbruck   
271112          Poland  POL  2014 Winter  2014  Winter           Sochi   
271113          Poland  POL  2014 Winter  2014  Winter           Sochi   
271114          Poland  POL  1998 Winter  1998  Winter          Nagano   
271115          Poland  POL  2002 Winter  2002  Winter  Salt Lake City   

                Sport                                     Event Medal  
0          Basketball               Basketball Men's Basketball   NaN  
1                Judo              Judo Men's Extra-Lightweight   NaN  
2            Football                   Football Men's Football   NaN  
3          Tug-Of-War               Tug-Of-War Men's Tug-Of-War  Gold  
4       Speed Skating          Speed Skating Women's 500 metres   NaN  
...               ...                                       ...   ...  
271111           Luge                Luge Mixed (Men)'s Doubles   NaN  
271112    Ski Jumping  Ski Jumping Men's Large Hill, Individual   NaN  
271113    Ski Jumping        Ski Jumping Men's Large Hill, Team   NaN  
271114      Bobsleigh                      Bobsleigh Men's Four   NaN  
271115      Bobsleigh                      Bobsleigh Men's Four   NaN  

[271116 rows x 15 columns]

In [6]:
df.head()

ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China   
1   2                  A Lamusi   M  23.0   170.0    60.0           China   
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   

   NOC        Games  Year  Season       City          Sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer     London           Judo   
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN

In [8]:
df.describe()

ID            Age         Height         Weight  \
count  271116.000000  261642.000000  210945.000000  208241.000000   
mean    68248.954396      25.556898     175.338970      70.702393   
std     39022.286345       6.393561      10.518462      14.348020   
min         1.000000      10.000000     127.000000      25.000000   
25%     34643.000000      21.000000     168.000000      60.000000   
50%     68205.000000      24.000000     175.000000      70.000000   
75%    102097.250000      28.000000     183.000000      79.000000   
max    135571.000000      97.000000     226.000000     214.000000   

                Year  
count  271116.000000  
mean     1978.378480  
std        29.877632  
min      1896.000000  
25%      1960.000000  
50%      1988.000000  
75%      2002.000000  
max      2016.000000

In [10]:
df.shape

(271116, 15)

#### rastgele 5 satır

In [11]:
df.sample(5, random_state=42)

ID                                       Name Sex   Age  Height  \
195789   98308                              Khalid Raghib   M  22.0   180.0   
243016  121701                    Mrioara Trac (-Curelea)   F  21.0   172.0   
265866  133023                       Martin Laumann Ylven   M  21.0   190.0   
144505   72524  Wilhelm Bernhard Adolf Emil "Willy" Ltzow   M  19.0     NaN   
150954   75751                        Jess Martnez Tejeda   M  20.0   163.0   

        Weight     Team  NOC        Games  Year  Season         City  \
195789    70.0  Morocco  MAR  1992 Summer  1992  Summer    Barcelona   
243016    68.0  Romania  ROU  1984 Summer  1984  Summer  Los Angeles   
265866    92.0   Norway  NOR  2010 Winter  2010  Winter    Vancouver   
144505     NaN  Germany  GER  1912 Summer  1912  Summer    Stockholm   
150954    48.0   Mexico  MEX  1996 Summer  1996  Summer      Atlanta   

             Sport                                   Event   Medal  
195789    Football                 Football Men's Football     NaN  
243016      Rowing             Rowing Women's Coxed Eights  Silver  
265866  Ice Hockey             Ice Hockey Men's Ice Hockey     NaN  
144505    Swimming  Swimming Men's 400 metres Breaststroke     NaN  
150954      Boxing            Boxing Men's Light-Flyweight     NaN

#### tekrar eden ID'ler

In [24]:
df["ID"].nunique()

135571

In [25]:
df["ID"].unique(), len(df)

(array([     1,      2,      3, ..., 135569, 135570, 135571]), 271116)

In [14]:
df.groupby("ID").size().sort_values(ascending=False).head(10)

ID
77710     58
106296    39
115354    38
119591    36
129196    32
44875     32
53240     32
119590    32
89187     32
106156    31
dtype: int64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271116 entries, 0 to 271115
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   ID      271116 non-null  int64  
 1   Name    271116 non-null  object 
 2   Sex     271116 non-null  object 
 3   Age     261642 non-null  float64
 4   Height  210945 non-null  float64
 5   Weight  208241 non-null  float64
 6   Team    271116 non-null  object 
 7   NOC     271116 non-null  object 
 8   Games   271116 non-null  object 
 9   Year    271116 non-null  int64  
 10  Season  271116 non-null  object 
 11  City    271116 non-null  object 
 12  Sport   271116 non-null  object 
 13  Event   271116 non-null  object 
 14  Medal   39783 non-null   object 
dtypes: float64(3), int64(2), object(10)
memory usage: 31.0+ MB


In [16]:
df.dtypes

ID          int64
Name       object
Sex        object
Age       float64
Height    float64
Weight    float64
Team       object
NOC        object
Games      object
Year        int64
Season     object
City       object
Sport      object
Event      object
Medal      object
dtype: object

#### Missing (eksik) değer taraması

In [20]:
missing = df.isna().mean().sort_values(ascending=False)*100

In [21]:
missing

Medal     85.326207
Weight    23.191180
Height    22.193821
Age        3.494445
ID         0.000000
Name       0.000000
Sex        0.000000
Team       0.000000
NOC        0.000000
Games      0.000000
Year       0.000000
Season     0.000000
City       0.000000
Sport      0.000000
Event      0.000000
dtype: float64

In [19]:
missing.round(2).head(10)

Medal     85.33
Weight    23.19
Height    22.19
Age        3.49
ID         0.00
Name       0.00
Sex        0.00
Team       0.00
NOC        0.00
Games      0.00
dtype: float64

In [22]:
df["Medal_filled"]= df["Medal"].fillna("No Medal")
df["Medal_filled"].value_counts()

Medal_filled
No Medal    231333
Gold         13372
Bronze       13295
Silver       13116
Name: count, dtype: int64

#### Duplicate (yinelenen) kontrolü - önce “tam satır”, sonra “mantıksal anahtar”

veri şişmiş mi? aynı kayıtşar kopyalanmış mı

In [26]:
df.duplicated().sum()

np.int64(1385)

In [28]:
df[df.duplicated()].head(10)

ID                           Name Sex   Age  Height  Weight  \
1252   704             Dsir Antoine Acket   M  27.0     NaN     NaN   
4282  2449         William Truman Aldrich   M  48.0     NaN     NaN   
4283  2449         William Truman Aldrich   M  48.0     NaN     NaN   
4862  2777         Hermann Reinhard Alker   M  43.0     NaN     NaN   
4864  2777         Hermann Reinhard Alker   M  43.0     NaN     NaN   
4867  2777         Hermann Reinhard Alker   M  51.0     NaN     NaN   
5105  2903  Lucien Charles Edouard Alliot   M  46.0     NaN     NaN   
5106  2903  Lucien Charles Edouard Alliot   M  46.0     NaN     NaN   
7770  4319                 Ludwig Angerer   M  41.0     NaN     NaN   
7771  4319                 Ludwig Angerer   M  41.0     NaN     NaN   

               Team  NOC        Games  Year  Season         City  \
1252        Belgium  BEL  1932 Summer  1932  Summer  Los Angeles   
4282  United States  USA  1928 Summer  1928  Summer    Amsterdam   
4283  United States  USA  1928 Summer  1928  Summer    Amsterdam   
4862        Germany  GER  1928 Summer  1928  Summer    Amsterdam   
4864        Germany  GER  1928 Summer  1928  Summer    Amsterdam   
4867        Germany  GER  1936 Summer  1936  Summer       Berlin   
5105         France  FRA  1924 Summer  1924  Summer        Paris   
5106         France  FRA  1924 Summer  1924  Summer        Paris   
7770        Germany  GER  1932 Summer  1932  Summer  Los Angeles   
7771        Germany  GER  1932 Summer  1932  Summer  Los Angeles   

                 Sport                                              Event  \
1252  Art Competitions     Art Competitions Mixed Painting, Unknown Event   
4282  Art Competitions  Art Competitions Mixed Painting, Drawings And ...   
4283  Art Competitions  Art Competitions Mixed Painting, Drawings And ...   
4862  Art Competitions  Art Competitions Mixed Architecture, Designs F...   
4864  Art Competitions  Art Competitions Mixed Architecture, Architect...   
4867  Art Competitions  Art Competitions Mixed Architecture, Unknown E...   
5105  Art Competitions                 Art Competitions Mixed Sculpturing   
5106  Art Competitions                 Art Competitions Mixed Sculpturing   
7770  Art Competitions     Art Competitions Mixed Painting, Unknown Event   
7771  Art Competitions     Art Competitions Mixed Painting, Unknown Event   

     Medal Medal_filled  
1252   NaN     No Medal  
4282   NaN     No Medal  
4283   NaN     No Medal  
4862   NaN     No Medal  
4864   NaN     No Medal  
4867   NaN     No Medal  
5105   NaN     No Medal  
5106   NaN     No Medal  
7770   NaN     No Medal  
7771   NaN     No Medal

#### Mantıksal anahtar duplicate

In [29]:
key_cols= ["ID","Games","Event"]
dup_key =df.duplicated(subset=key_cols).sum()
dup_key

np.int64(1480)

In [30]:
df[df.duplicated(subset=key_cols,keep=False)].sort_values(key_cols).head(20)

ID                           Name Sex   Age  Height  Weight  \
1251   704             Dsir Antoine Acket   M  27.0     NaN     NaN   
1252   704             Dsir Antoine Acket   M  27.0     NaN     NaN   
4017  2317                 Auguste Albert   M   NaN     NaN     NaN   
4018  2317                 Auguste Albert   M   NaN     NaN     NaN   
4281  2449         William Truman Aldrich   M  48.0     NaN     NaN   
4282  2449         William Truman Aldrich   M  48.0     NaN     NaN   
4283  2449         William Truman Aldrich   M  48.0     NaN     NaN   
4863  2777         Hermann Reinhard Alker   M  43.0     NaN     NaN   
4864  2777         Hermann Reinhard Alker   M  43.0     NaN     NaN   
4861  2777         Hermann Reinhard Alker   M  43.0     NaN     NaN   
4862  2777         Hermann Reinhard Alker   M  43.0     NaN     NaN   
4866  2777         Hermann Reinhard Alker   M  51.0     NaN     NaN   
4867  2777         Hermann Reinhard Alker   M  51.0     NaN     NaN   
5104  2903  Lucien Charles Edouard Alliot   M  46.0     NaN     NaN   
5105  2903  Lucien Charles Edouard Alliot   M  46.0     NaN     NaN   
5106  2903  Lucien Charles Edouard Alliot   M  46.0     NaN     NaN   
7769  4319                 Ludwig Angerer   M  41.0     NaN     NaN   
7770  4319                 Ludwig Angerer   M  41.0     NaN     NaN   
7771  4319                 Ludwig Angerer   M  41.0     NaN     NaN   
7772  4319                 Ludwig Angerer   M  41.0     NaN     NaN   

               Team  NOC        Games  Year  Season         City  \
1251        Belgium  BEL  1932 Summer  1932  Summer  Los Angeles   
1252        Belgium  BEL  1932 Summer  1932  Summer  Los Angeles   
4017       Martha-1  FRA  1900 Summer  1900  Summer        Paris   
4018       Martha-1  FRA  1900 Summer  1900  Summer        Paris   
4281  United States  USA  1928 Summer  1928  Summer    Amsterdam   
4282  United States  USA  1928 Summer  1928  Summer    Amsterdam   
4283  United States  USA  1928 Summer  1928  Summer    Amsterdam   
4863        Germany  GER  1928 Summer  1928  Summer    Amsterdam   
4864        Germany  GER  1928 Summer  1928  Summer    Amsterdam   
4861        Germany  GER  1928 Summer  1928  Summer    Amsterdam   
4862        Germany  GER  1928 Summer  1928  Summer    Amsterdam   
4866        Germany  GER  1936 Summer  1936  Summer       Berlin   
4867        Germany  GER  1936 Summer  1936  Summer       Berlin   
5104         France  FRA  1924 Summer  1924  Summer        Paris   
5105         France  FRA  1924 Summer  1924  Summer        Paris   
5106         France  FRA  1924 Summer  1924  Summer        Paris   
7769        Germany  GER  1932 Summer  1932  Summer  Los Angeles   
7770        Germany  GER  1932 Summer  1932  Summer  Los Angeles   
7771        Germany  GER  1932 Summer  1932  Summer  Los Angeles   
7772        Germany  GER  1932 Summer  1932  Summer  Los Angeles   

                 Sport                                              Event  \
1251  Art Competitions     Art Competitions Mixed Painting, Unknown Event   
1252  Art Competitions     Art Competitions Mixed Painting, Unknown Event   
4017           Sailing                              Sailing Mixed 1-2 Ton   
4018           Sailing                              Sailing Mixed 1-2 Ton   
4281  Art Competitions  Art Competitions Mixed Painting, Drawings And ...   
4282  Art Competitions  Art Competitions Mixed Painting, Drawings And ...   
4283  Art Competitions  Art Competitions Mixed Painting, Drawings And ...   
4863  Art Competitions  Art Competitions Mixed Architecture, Architect...   
4864  Art Competitions  Art Competitions Mixed Architecture, Architect...   
4861  Art Competitions  Art Competitions Mixed Architecture, Designs F...   
4862  Art Competitions  Art Competitions Mixed Architecture, Designs F...   
4866  Art Competitions  Art Competitions Mixed Architecture, Unknown E...   
4867  Art Competitions  Art Competitions Mixed Architecture, Unknown E...   
5104  Art

#### temel istatistik

Neyi elde ederiz: sayısal dağılımlar, uç değerler, mantık dışı değerler
Niye öğreniyoruz: model/analiz öncesi “veri saçma mı?” kontrolü şart

In [31]:
df[["Age","Height","Weight"]].describe()

Age         Height         Weight
count  261642.000000  210945.000000  208241.000000
mean       25.556898     175.338970      70.702393
std         6.393561      10.518462      14.348020
min        10.000000     127.000000      25.000000
25%        21.000000     168.000000      60.000000
50%        24.000000     175.000000      70.000000
75%        28.000000     183.000000      79.000000
max        97.000000     226.000000     214.000000

In [33]:
(df["Age"]<0).sum(), (df["Age"]>80).sum()

(df["Height"]<100).sum(), (df["Height"]>230).sum()
(df["Weight"]<30).sum(), (df["Weight"]>200).sum()

(np.int64(20), np.int64(2))

#### Kategorik sütunlarda “temizlik ihtiyacı” kontrolü

Neyi elde ederiz: yazım farkları, boşluk, büyük-küçük harf sorunları
Niye öğreniyoruz: “İstanbul” ve “istanbul ” ayrı kategori sayılır → analiz bozulur

In [36]:
df["City"].nunique()
df["City"].value_counts().head(20)

City
London            22426
Athina            15556
Sydney            13821
Atlanta           13780
Rio de Janeiro    13688
Beijing           13602
Barcelona         12977
Los Angeles       12423
Seoul             12037
Munich            10304
Montreal           8641
Mexico City        8588
Helsinki           8270
Roma               8119
Tokyo              7702
Moskva             7191
Paris              7169
Berlin             6506
Amsterdam          4992
Sochi              4891
Name: count, dtype: int64

boşluk kırpma (genel temizlik)

In [37]:
for col in ["Team","City","Sport","Event", "NOC"]:
    df[col]=df[col].astype(str).str.strip()

#### Zaman var: trend analizi için “yıl bazına indir”

Neyi elde ederiz: yıllara göre katılım, madalya sayısı trendi
Niye öğreniyoruz: zaman boyutu analiz stratejisini tamamen değiştirir

In [38]:
df.groupby("Year").size().head()

Year
1896     380
1900    1936
1904    1301
1906    1733
1908    3101
dtype: int64

In [40]:
medals_by_year= df.dropna(subset=["Medal"]).groupby("Year").size()
medals_by_year.head()

Year
1896    143
1900    604
1904    486
1906    458
1908    831
dtype: int64

In [41]:
year_total = df.groupby("Year").size()
year_medal = df["Medal"].notna().groupby(df["Year"]).sum()

medal_rate=(year_medal/year_total).sort_index()
medal_rate.head()

Year
1896    0.376316
1900    0.311983
1904    0.373559
1906    0.264282
1908    0.267978
dtype: float64