In [ ]:
import numpy as np

In [2]:
my_list = [10,20,30,40,50]

In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([10, 20, 30, 40, 50])

In [14]:
type(np)

module

In [15]:
type(np.array)


list

In [5]:
my_numpy_array= np.array(my_list)

In [6]:
type(my_numpy_array)

numpy.ndarray

In [7]:
my_numpy_array.max()

50

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.random.random()

0.5176957715616783

In [12]:
np.random.random(4)

array([0.43331479, 0.91614496, 0.81561909, 0.7441324 ])

#### Array Arithmetic


In [13]:
my_list1=[1,2,3]

In [14]:
my_list2=[4,5,6]

In [15]:
my_list1+my_list2

[1, 2, 3, 4, 5, 6]

In [16]:
my_numpy_array1= np.array(my_list1)

In [17]:
my_numpy_array2=np.array(my_list2)

In [18]:
my_numpy_array1+my_numpy_array2

array([5, 7, 9])

In [19]:
my_numpy_array1*my_numpy_array2

array([ 4, 10, 18])

In [20]:
my_numpy_array1/my_numpy_array2

array([0.25, 0.4 , 0.5 ])

In [21]:
my_numpy_array1*5

array([ 5, 10, 15])

In [22]:
my_list*5

[10,
 20,
 30,
 40,
 50,
 10,
 20,
 30,
 40,
 50,
 10,
 20,
 30,
 40,
 50,
 10,
 20,
 30,
 40,
 50,
 10,
 20,
 30,
 40,
 50]

In [23]:
other_array=np.array([10,20,30,40,50])

In [24]:
other_array.min()

10

In [25]:
other_array.max()

50

#### arrange & indexing

In [26]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
np_array=np.arange(0,10)

In [30]:
np_array[0]

0

In [32]:
np_array[-1]

9

In [33]:
np_array[1:4:]

array([1, 2, 3])

In [34]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [35]:
np_array[2:6:2]

array([2, 4])

In [36]:
np.random.randn(6)

array([ 1.89772264, -1.46986974,  2.19145835, -0.08704115, -0.65158299,
        0.02945297])

In [37]:
np.random.randn(4,3)

array([[ 1.99335066,  0.89481583, -0.32783592],
       [ 0.76505971, -0.67960583,  0.1593673 ],
       [ 0.77909969, -0.23530524, -0.72697515],
       [-1.37519572,  0.50404863, -0.43468477]])

In [38]:
np.random.randint(1,300,5)

array([106,  71, 248, 128,  52])