In [4]:
import numpy as np

In [ ]:
my_matrix=[[5,10],[15,20]]

row * column

In [ ]:
numpy_matrix = np.array([[5,10],[15,20]])

In [6]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [7]:
numpy_matrix.shape

(2, 2)

In [8]:
numpy_matrix.sum()

np.int64(50)

In [9]:
numpy_matrix.sum

<function ndarray.sum>

In [12]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.zeros((4,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

##### matrix arithmetic

In [14]:
first_array=np.array([[10,20],[30,40]])

In [15]:
second_array=np.array([[50,60],[70,80]])

In [16]:
first_array+second_array

array([[ 60,  80],
       [100, 120]])

In [17]:
first_array

array([[10, 20],
       [30, 40]])

In [18]:
third_array =np.array([[50,60]])

In [19]:
first_array+third_array

array([[ 60,  80],
       [ 80, 100]])

In [20]:
fourth_array=np.array([[10,20,30,40,50,60]])

In [ ]:
# arrayler birbirleriyle uyumsuz oldukları için hata cıkıyor

irst_array+fourth_array

ValueError: operands could not be broadcast together with shapes (2,2) (1,6) 

In [22]:
first_array*2

array([[20, 40],
       [60, 80]])

In [24]:
third_array=np.array([[10],[20]])

In [25]:
third_array

array([[10],
       [20]])

In [27]:
third_array.shape

(2, 1)

In [28]:
first_array*third_array


array([[100, 200],
       [600, 800]])

### matrix multiplication

In [29]:
first_array*second_array

array([[ 500, 1200],
       [2100, 3200]])

#### dot product

In [34]:
first_array.shape

(2, 2)

In [35]:
second_array.shape

(2, 2)

In [ ]:
#row ve column sayıları aynı olmalı

In [36]:
result_matrix=first_array.dot(second_array)

In [37]:
result_matrix.shape

(2, 2)