In [ ]:
import numpy as np

In [2]:
my_list = [10,20,30,40,50]

In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([10, 20, 30, 40, 50])

In [14]:
type(np)

module

In [15]:
type(np.array)


list

In [5]:
my_numpy_array= np.array(my_list)

In [6]:
type(my_numpy_array)

numpy.ndarray

In [7]:
my_numpy_array.max()

50

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.random.random()

0.5176957715616783

In [12]:
np.random.random(4)

array([0.43331479, 0.91614496, 0.81561909, 0.7441324 ])