In [1]:
import numpy as np

In [2]:
new_array=np.random.randint(1,100,20)

In [3]:
new_array

array([37, 64, 70, 80, 54, 18, 58, 21, 32, 99, 94, 27, 16, 96,  7, 14, 65,
       91, 35, 54])

In [4]:
new_array > 25

array([ True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True, False,  True, False, False,  True,  True,
        True,  True])

In [5]:
new_array[new_array>25]

array([37, 64, 70, 80, 54, 58, 32, 99, 94, 27, 96, 65, 91, 35, 54])

In [6]:
new_array[new_array<25]

array([18, 21, 16,  7, 14])

#### transpose & reshape

In [7]:
matrix_a=np.array([[10,20],[20,30],[30,40]])

In [8]:
matrix_a

array([[10, 20],
       [20, 30],
       [30, 40]])

In [9]:
matrix_a.shape

(3, 2)

In [ ]:
# rowlar ve columnların yerini değiştirir

matrix_a.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [ ]:
matrix_a.T # aynısını yapar

array([[10, 20, 30],
       [20, 30, 40]])

In [13]:
random_array=np.random.random((6,1))

In [14]:
random_array.shape

(6, 1)

In [15]:
random_array.reshape(2,3)

array([[0.96908025, 0.19275082, 0.57078039],
       [0.28084762, 0.67208995, 0.23635178]])

In [16]:
random_array.reshape(3,2)

array([[0.96908025, 0.19275082],
       [0.57078039, 0.28084762],
       [0.67208995, 0.23635178]])

#### z-score

In [17]:
data= np.array([10,12,13,15,18,25,100,105])

#### outlier

In [18]:
mean=np.mean(data)

In [19]:
mean

np.float64(37.25)

In [20]:
data.sum()/len(data)

np.float64(37.25)

In [21]:
std=np.std(data)

In [22]:
std

np.float64(37.9333296719389)

In [23]:
z_scores=(data-mean)/std

In [24]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [26]:
data[z_scores>1]

array([100, 105])

In [27]:
#math equation

In [28]:
# 2x + 3y = 8 ve 5x + 7y = 19

In [29]:
#coefficient

In [30]:
A =np.array([[2,3],[5,7]])

In [31]:
#constant
b=np.array([8,19])

In [32]:
solution= np.linalg.solve(A,b)

In [33]:
solution

array([1., 2.])